name: Deployment
on:
  push:
    branches-ignore: ["*"]
    tags: ["*"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    container: python:3.8-alpine
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Build package
        run: python3 setup.py sdist
      - name: Publish package Test
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
      - name: Publish package
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags') && github.repository == 'saripirala/bin-optimize'
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
